# Generated by Django 3.0.8 on 2020-08-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FAS', 'Fashion'), ('TOY', 'Toys'), ('ELC', 'Electronics'), ('HOM', 'Home')], default='HOM', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=500)),
                ('start_bid', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image_url', models.CharField(max_length=64)),
            ],
        ),
    ]
