# Generated by Django 3.0.8 on 2020-08-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200810_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cateogry',
            field=models.CharField(choices=[('F', 'Fashion'), ('T', 'Toys'), ('E', 'Electronics'), ('H', 'Home')], default='H', max_length=10),
        ),
    ]
