# Generated by Django 3.0.8 on 2020-08-11 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200810_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='cateogry',
            new_name='category',
        ),
    ]
